# -*- coding: utf-8 -*-
import io
p = ((P))
s = io.open(p, encoding=((E))).read()
old = (
    ((OL1))
    ((OL2))
    ((OL3))
    ((OL4))
    ((OL5))
)
new = (
    ((NL1))
    ((NL2))
    ((NL3))
    ((NL4))
    ((NL5))
    ((NL6))
    ((NL7))
    ((NL8))
    ((NL9))
    ((NL10))
    ((NL11))
)
assert old in s, ((A1))
s = s.replace(old, new, 1)
imp = ((IMP))
s = s.replace(imp, imp + ((AUTH_IMP)) + ((AUTHDB)) + chr(10), 1)
io.open(p, ((W)), encoding=((E))).write(s)
print(((DONE)))